version: "3.3"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_site:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.dev
volumes:
  postgres_site: