version: "3.3"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web_site
    ports:
      - 8000:8000
    env_file:
      - ./.env.map
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - postgis
  postgis:
    image: mdillon/postgis
    container_name: postgis_con
    # networks:
    #   - my_network
    env_file:
      - ./.env.db.dev
    volumes:
      - postgres_maps:/var/lib/postgresql/data/
      - ./data:/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_con
    env_file:
      - ./.env.pgadmin
    # networks:
    #   - my_network
    ports:
      - 80:80
    depends_on:
      - postgis
# networks:
#   my_network:
#     driver: bridge
volumes:
  postgres_maps:
